prompt --application/deployment/install/install_data_model
begin
--   Manifest
--     INSTALL: INSTALL-Data Model
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.0'
,p_default_workspace_id=>146726770692635976661
,p_default_application_id=>192092
,p_default_id_offset=>8155984660337852939
,p_default_owner=>'WKSP_KCSI'
);
wwv_flow_imp.g_varchar2_table := wwv_flow_imp.empty_varchar2_table;
wwv_flow_imp.g_varchar2_table(1) := '  CREATE TABLE "SM_POSTS" '||wwv_flow.LF||
'   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXV';
wwv_flow_imp.g_varchar2_table(2) := 'ALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOS';
wwv_flow_imp.g_varchar2_table(3) := 'CALE  NOT NULL ENABLE, '||wwv_flow.LF||
'	"POST_COMMENT" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"FILE_BLOB" BLOB, '||wwv_flow.LF||
'	"FILE_MIME" VARCH';
wwv_flow_imp.g_varchar2_table(4) := 'AR2(255 CHAR), '||wwv_flow.LF||
'	"FILE_NAME" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"LAT" NUMBER, '||wwv_flow.LF||
'	"LON" NUMBER, '||wwv_flow.LF||
'	"CREATED" DATE NO';
wwv_flow_imp.g_varchar2_table(5) := 'T NULL ENABLE, '||wwv_flow.LF||
'	"CREATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, '||wwv_flow.LF||
'	"UPDATED" DATE NOT NULL ENABLE, ';
wwv_flow_imp.g_varchar2_table(6) := ''||wwv_flow.LF||
'	"UPDATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, '||wwv_flow.LF||
'	 CONSTRAINT "SM_POSTS_ID_PK" PRIMARY KEY ("ID")';
wwv_flow_imp.g_varchar2_table(7) := ''||wwv_flow.LF||
'  USING INDEX  ENABLE'||wwv_flow.LF||
'   ) ;'||wwv_flow.LF||
''||wwv_flow.LF||
'  CREATE TABLE "SM_REACTIONS" '||wwv_flow.LF||
'   (	"ID" NUMBER GENERATED BY DEFAULT ';
wwv_flow_imp.g_varchar2_table(8) := 'ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CAC';
wwv_flow_imp.g_varchar2_table(9) := 'HE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, '||wwv_flow.LF||
'	"POST_ID" NUMBER, '||wwv_flow.LF||
'	"REACTION" VARCHAR2(';
wwv_flow_imp.g_varchar2_table(10) := '16 CHAR), '||wwv_flow.LF||
'	"LAT" NUMBER, '||wwv_flow.LF||
'	"LON" NUMBER, '||wwv_flow.LF||
'	"CREATED" DATE NOT NULL ENABLE, '||wwv_flow.LF||
'	"CREATED_BY" VARCHAR2(';
wwv_flow_imp.g_varchar2_table(11) := '255 CHAR) NOT NULL ENABLE, '||wwv_flow.LF||
'	"UPDATED" DATE NOT NULL ENABLE, '||wwv_flow.LF||
'	"UPDATED_BY" VARCHAR2(255 CHAR) NOT N';
wwv_flow_imp.g_varchar2_table(12) := 'ULL ENABLE, '||wwv_flow.LF||
'	 CONSTRAINT "SM_REACTIONS_ID_PK" PRIMARY KEY ("ID")'||wwv_flow.LF||
'  USING INDEX  ENABLE, '||wwv_flow.LF||
'	 CONSTRAI';
wwv_flow_imp.g_varchar2_table(13) := 'NT "SM_REACTIONS_CON" UNIQUE ("POST_ID", "CREATED_BY")'||wwv_flow.LF||
'  USING INDEX  ENABLE'||wwv_flow.LF||
'   ) ;'||wwv_flow.LF||
''||wwv_flow.LF||
' '||wwv_flow.LF||
'create or rep';
wwv_flow_imp.g_varchar2_table(14) := 'lace trigger sm_posts_biu '||wwv_flow.LF||
'    before insert or update '||wwv_flow.LF||
'    on sm_posts '||wwv_flow.LF||
'    for each row '||wwv_flow.LF||
'begin '||wwv_flow.LF||
'  ';
wwv_flow_imp.g_varchar2_table(15) := '  if inserting then '||wwv_flow.LF||
'        :new.created := sysdate; '||wwv_flow.LF||
'        :new.created_by := coalesce(sys_conte';
wwv_flow_imp.g_varchar2_table(16) := 'xt(''APEX$SESSION'',''APP_USER''),user); '||wwv_flow.LF||
'    end if; '||wwv_flow.LF||
'    :new.updated := sysdate; '||wwv_flow.LF||
'    :new.updated_by';
wwv_flow_imp.g_varchar2_table(17) := ' := coalesce(sys_context(''APEX$SESSION'',''APP_USER''),user); '||wwv_flow.LF||
'end sm_posts_biu;'||wwv_flow.LF||
'/'||wwv_flow.LF||
'create or replace tr';
wwv_flow_imp.g_varchar2_table(18) := 'igger sm_reactions_biu '||wwv_flow.LF||
'    before insert or update '||wwv_flow.LF||
'    on sm_reactions '||wwv_flow.LF||
'    for each row '||wwv_flow.LF||
'begin '||wwv_flow.LF||
' ';
wwv_flow_imp.g_varchar2_table(19) := '   if inserting then '||wwv_flow.LF||
'        :new.created := sysdate; '||wwv_flow.LF||
'        :new.created_by := coalesce(sys_cont';
wwv_flow_imp.g_varchar2_table(20) := 'ext(''APEX$SESSION'',''APP_USER''),user); '||wwv_flow.LF||
'    end if; '||wwv_flow.LF||
'    :new.updated := sysdate; '||wwv_flow.LF||
'    :new.updated_b';
wwv_flow_imp.g_varchar2_table(21) := 'y := coalesce(sys_context(''APEX$SESSION'',''APP_USER''),user); '||wwv_flow.LF||
'end sm_reactions_biu;'||wwv_flow.LF||
'/ ';
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(9840489840796509298)
,p_install_id=>wwv_flow_imp.id(9840141003865487908)
,p_name=>'Data Model'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_imp.varchar2_to_clob(wwv_flow_imp.g_varchar2_table)
,p_created_on=>wwv_flow_imp.dz('20260519061015Z')
,p_updated_on=>wwv_flow_imp.dz('20260519061015Z')
,p_created_by=>'ANKITABERI14@GMAIL.COM'
,p_updated_by=>'ANKITABERI14@GMAIL.COM'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(9840489939201509299)
,p_script_id=>wwv_flow_imp.id(9840489840796509298)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SM_POSTS'
,p_created_on=>wwv_flow_imp.dz('20260519061015Z')
,p_last_updated_on=>wwv_flow_imp.dz('20260519061015Z')
,p_created_by=>'ANKITABERI14@GMAIL.COM'
,p_last_updated_by=>'ANKITABERI14@GMAIL.COM'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(9840490073047509300)
,p_script_id=>wwv_flow_imp.id(9840489840796509298)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SM_REACTIONS'
,p_created_on=>wwv_flow_imp.dz('20260519061015Z')
,p_last_updated_on=>wwv_flow_imp.dz('20260519061015Z')
,p_created_by=>'ANKITABERI14@GMAIL.COM'
,p_last_updated_by=>'ANKITABERI14@GMAIL.COM'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(9840490304632509300)
,p_script_id=>wwv_flow_imp.id(9840489840796509298)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TRIGGER'
,p_object_name=>'SM_POSTS_BIU'
,p_created_on=>wwv_flow_imp.dz('20260519061015Z')
,p_last_updated_on=>wwv_flow_imp.dz('20260519061015Z')
,p_created_by=>'ANKITABERI14@GMAIL.COM'
,p_last_updated_by=>'ANKITABERI14@GMAIL.COM'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(9840490552409509300)
,p_script_id=>wwv_flow_imp.id(9840489840796509298)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TRIGGER'
,p_object_name=>'SM_REACTIONS_BIU'
,p_created_on=>wwv_flow_imp.dz('20260519061015Z')
,p_last_updated_on=>wwv_flow_imp.dz('20260519061015Z')
,p_created_by=>'ANKITABERI14@GMAIL.COM'
,p_last_updated_by=>'ANKITABERI14@GMAIL.COM'
);
wwv_flow_imp.component_end;
end;
/
